/**
 * Seed data for Payments Atlas.
 * Populates all tables with realistic payments industry data.
 */

// Helper: generate features for a given layer
function genFeatures(layer, category, items) {
  return items.map(([name, desc, complexity]) => ({
    name, description: desc, layer, category,
    actors: ['{}'], metrics_impacted: ['{}'], problems_solved: ['{}'],
    complexity: complexity || 'medium', metadata: '{}'
  }));
}

exports.seed = async function(knex) {
  // Clear all tables in reverse dependency order
  const tables = ['taxonomy','ecosystem_players','diagnosis_rules','scenarios',
    'metrics','solutions','problems','transaction_steps','transaction_flows',
    'actors','payment_rails','feature_business_rules','feature_dependencies','payment_features'];
  for (const t of tables) await knex(t).del();

  // ========== PAYMENT FEATURES (300) ==========
  const features = [
    // Experience Layer (50)
    ...genFeatures('experience','experience',[
      ['Checkout UI','Hosted checkout page with payment method selection','low'],
      ['One-Click Pay','Single-click payment for returning customers','medium'],
      ['Guest Checkout','Payment without account creation','low'],
      ['Saved Cards','Store and reuse card credentials','medium'],
      ['Mobile SDK','Native mobile payment integration','high'],
      ['Drop-in UI','Pre-built payment form component','low'],
      ['Payment Links','Shareable payment URLs','low'],
      ['QR Code Payment','Scan-to-pay QR code generation','medium'],
      ['Hosted Payment Page','Redirect-based payment page','low'],
      ['Embedded Checkout','Inline checkout within merchant site','medium'],
      ['Express Checkout','Accelerated payment flow','medium'],
      ['Payment Method Selection','Dynamic payment method display','low'],
      ['Card Input Validation','Real-time card number validation','low'],
      ['Address Verification UI','Address collection and verification form','low'],
      ['Multi-step Checkout','Wizard-based checkout flow','medium'],
      ['Cart Recovery','Abandoned cart email triggers','medium'],
      ['Payment Status Page','Real-time payment status display','low'],
      ['Receipt Generation','Digital receipt creation','low'],
      ['Localized Checkout','Multi-language payment forms','medium'],
      ['Accessibility Compliance','WCAG-compliant payment forms','medium'],
      ['Dark Mode Checkout','Dark theme payment interface','low'],
      ['Custom Branding','White-label payment forms','low'],
      ['Progressive Disclosure','Show fields progressively based on input','medium'],
      ['Auto-fill Support','Browser auto-fill integration','low'],
      ['Error Recovery UI','User-friendly error handling in checkout','low'],
      ['Installment Selection UI','Installment plan picker in checkout','medium'],
      ['Tip Selection','Add tip/gratuity in checkout','low'],
      ['Donation Add-on','Optional donation during checkout','low'],
      ['Gift Card Input','Gift card redemption in checkout','medium'],
      ['Loyalty Points Display','Show redeemable loyalty points','medium'],
      ['Shipping Calculator','Real-time shipping cost calculation','medium'],
      ['Tax Calculator UI','Dynamic tax calculation display','medium'],
      ['Currency Selector','Let customer choose payment currency','medium'],
      ['Promo Code Input','Discount code application','low'],
      ['Order Summary','Itemized order review before payment','low'],
      ['Payment Animation','Loading and success animations','low'],
      ['Biometric Prompt','Fingerprint/Face ID payment confirmation','high'],
      ['Voice Payment','Voice-activated payment initiation','critical'],
      ['Chatbot Payment','Payment within chat interface','high'],
      ['Social Commerce Checkout','In-app social media checkout','high'],
      ['Subscription Signup','Recurring payment enrollment flow','medium'],
      ['Trial Period Flow','Free trial with payment method collection','medium'],
      ['Upgrade/Downgrade Flow','Plan change with prorated billing','medium'],
      ['Pay-by-Bank UI','Bank selection and auth redirect','medium'],
      ['Crypto Payment UI','Cryptocurrency payment interface','high'],
      ['BNPL Selection','Buy now pay later option display','medium'],
      ['Marketplace Checkout','Multi-seller cart checkout','high'],
      ['Invoice Payment Portal','Online invoice payment page','medium'],
      ['Recurring Donation','Scheduled donation setup','medium'],
      ['POS Integration','Point of sale terminal integration','high'],
    ]),
    // Orchestration Layer (50)
    ...genFeatures('orchestration','routing',[
      ['Smart Routing','Route transactions to optimal acquirer based on ML','high'],
      ['Cascade Routing','Failover to secondary acquirer on decline','high'],
      ['Cost-Based Routing','Route to lowest-cost acquirer','medium'],
      ['Geographic Routing','Route based on cardholder country','medium'],
      ['BIN-Based Routing','Route based on card BIN range','medium'],
      ['Load Balancing','Distribute volume across acquirers','medium'],
      ['A/B Testing Routing','Split traffic for performance testing','high'],
      ['Rules-Based Routing','Custom routing rules engine','medium'],
      ['Latency-Based Routing','Route to fastest responding acquirer','high'],
      ['Currency-Based Routing','Route based on transaction currency','medium'],
    ]),
    ...genFeatures('orchestration','orchestration',[
      ['Multi-PSP Orchestration','Manage multiple payment service providers','critical'],
      ['Provider Selection','Dynamic PSP selection logic','high'],
      ['Traffic Splitting','Percentage-based traffic distribution','medium'],
      ['Failover Management','Automatic provider failover','high'],
      ['Circuit Breaker','Stop routing to failing providers','high'],
      ['Provider Health Check','Monitor PSP availability','medium'],
      ['Routing Analytics','Track routing decision performance','medium'],
      ['Dynamic MID Selection','Select merchant ID per transaction','medium'],
      ['Acquirer Portfolio Management','Manage multiple acquirer relationships','high'],
      ['Payment Method Routing','Route by payment method type','medium'],
      ['Risk-Based Routing','Route based on transaction risk score','high'],
      ['Revenue Optimization','Maximize approval rate across providers','critical'],
      ['SLA Monitoring','Track provider SLA compliance','medium'],
      ['Webhook Management','Centralized webhook handling','medium'],
      ['Idempotency Service','Prevent duplicate transaction processing','high'],
      ['Request Queue','Queue and retry failed requests','medium'],
      ['Rate Limiting','Throttle API requests per provider','medium'],
      ['API Gateway','Unified API layer for all providers','high'],
      ['Event Bus','Async event processing pipeline','high'],
      ['Configuration Service','Dynamic feature flag management','medium'],
      ['Retry Orchestration','Coordinate retries across providers','high'],
      ['Timeout Management','Configurable timeout per provider','medium'],
      ['Rollback Orchestration','Coordinate refund/void across providers','high'],
      ['Multi-Currency Orchestration','Handle multi-currency across providers','high'],
      ['Batch Processing','Process bulk transactions','medium'],
      ['Scheduled Payments','Time-based payment execution','medium'],
      ['Payment Intent Management','Track payment lifecycle state','high'],
      ['Provider Credential Management','Secure API key management','high'],
      ['Migration Orchestration','Gradual provider migration tooling','critical'],
      ['Reconciliation Orchestration','Cross-provider reconciliation','high'],
      ['Provider Normalization','Normalize responses across providers','medium'],
      ['Error Code Mapping','Map provider errors to standard codes','medium'],
      ['Status Synchronization','Sync payment status across systems','medium'],
      ['Audit Trail','Complete transaction audit logging','medium'],
      ['Provider Sandbox','Test mode for each provider','medium'],
      ['Feature Flag Routing','Route based on feature availability','medium'],
      ['Canary Deployment','Gradual rollout of routing changes','high'],
      ['Provider Scorecard','Performance tracking per provider','medium'],
      ['Cost Analytics','Transaction cost analysis per route','medium'],
      ['Routing Simulation','Test routing rules before deployment','high'],
    ]),
    // Processing Layer (50)
    ...genFeatures('processing','processing',[
      ['Authorization','Request payment approval from issuer','medium'],
      ['Capture','Settle previously authorized payment','medium'],
      ['Refund','Return funds to customer','medium'],
      ['Void','Cancel authorized but uncaptured payment','medium'],
      ['Partial Capture','Capture less than authorized amount','medium'],
      ['Pre-Authorization','Reserve funds without capture intent','medium'],
      ['Incremental Authorization','Increase previously authorized amount','high'],
      ['BIN Lookup','Identify card type and issuer from BIN','medium'],
      ['Currency Conversion','Real-time FX rate conversion','high'],
      ['Multi-Currency Processing','Process in multiple currencies','high'],
      ['Recurring Billing','Automated subscription payments','high'],
      ['Installment Processing','Split payment into installments','high'],
      ['Split Payments','Distribute payment to multiple recipients','high'],
      ['Partial Refund','Refund portion of transaction','medium'],
      ['Batch Authorization','Bulk authorization processing','medium'],
      ['Delayed Capture','Capture after extended hold period','medium'],
      ['Auto-Capture','Automatic capture after authorization','low'],
      ['Reversal Processing','Process issuer-initiated reversals','medium'],
      ['Credit Processing','Issue credit without prior debit','medium'],
      ['Balance Inquiry','Check available card balance','low'],
      ['Card Verification','Validate card without charging','low'],
      ['AVS Check','Address verification service','medium'],
      ['CVV Verification','Card security code validation','low'],
      ['3D Secure Processing','Process 3DS authentication','high'],
      ['Surcharge Calculation','Calculate payment method surcharge','medium'],
      ['Convenience Fee','Apply convenience fee to transaction','low'],
      ['Tax Calculation','Calculate applicable taxes','medium'],
      ['Discount Application','Apply discounts and promotions','low'],
      ['Tip Processing','Process gratuity amounts','low'],
      ['Cash Back','Process cash back with purchase','medium'],
    ]),
    ...genFeatures('processing','tokenization',[
      ['PCI Vault','Secure cardholder data storage','critical'],
      ['Gateway Tokenization','PSP-level card tokenization','high'],
      ['Format-Preserving Tokenization','Tokens matching PAN format','high'],
      ['Multi-Use Tokens','Reusable payment tokens','medium'],
      ['Single-Use Tokens','One-time payment tokens','medium'],
      ['Token Lifecycle Management','Create, update, expire tokens','high'],
      ['Cross-Channel Tokenization','Tokens valid across channels','high'],
      ['Token Migration','Migrate tokens between providers','critical'],
      ['Detokenization Service','Retrieve original PAN from token','high'],
      ['Token Analytics','Track token usage and conversion','medium'],
    ]),
    ...genFeatures('processing','authentication',[
      ['3D Secure 2.x','EMV 3DS cardholder authentication','high'],
      ['3D Secure 1.0','Legacy 3DS authentication','medium'],
      ['Biometric Authentication','Fingerprint/facial recognition auth','critical'],
      ['OTP Authentication','One-time password verification','medium'],
      ['Risk-Based Authentication','Adaptive authentication based on risk','high'],
      ['Exemption Management','SCA exemption handling','high'],
      ['Delegated Authentication','Merchant-performed authentication','high'],
      ['Step-Up Authentication','Progressive authentication escalation','high'],
      ['Device Binding','Bind payment method to trusted device','high'],
      ['Behavioral Biometrics','Typing pattern and behavior analysis','critical'],
    ]),
    // Network Layer (50)
    ...genFeatures('network','tokenization',[
      ['Network Tokenization','Visa/MC network-level tokens','critical'],
      ['Scheme Token Provisioning','Issue tokens via card schemes','high'],
      ['Token Requestor ID','Register as network token requestor','high'],
      ['Network Token Lifecycle','Manage network token updates','high'],
      ['DPAN Management','Digital PAN management','high'],
    ]),
    ...genFeatures('network','processing',[
      ['ISO 8583 Messaging','Standard financial messaging protocol','high'],
      ['Account Updater','Auto-update expired/replaced cards','high'],
      ['Real-Time Account Updater','Instant card credential updates','critical'],
      ['Network Rules Engine','Card scheme rule compliance','high'],
      ['Interchange Optimization','Optimize interchange fee qualification','high'],
      ['Scheme Fee Management','Track and optimize scheme fees','medium'],
      ['Authorization Optimization','Enhance auth request data','high'],
      ['Network Score','Visa/MC transaction scoring','high'],
      ['Rapid Dispute Resolution','Automated dispute resolution via network','high'],
      ['Visa Direct','Push payments via Visa network','high'],
      ['Mastercard Send','Push payments via MC network','high'],
      ['Network Fraud Signals','Leverage scheme fraud indicators','high'],
      ['Decline Code Analysis','Interpret and act on decline codes','medium'],
      ['Soft Decline Handling','Retry soft declines with updated data','high'],
      ['Hard Decline Classification','Categorize non-retryable declines','medium'],
      ['Network Tokenization Analytics','Track network token performance','medium'],
      ['Cross-Border Optimization','Optimize international transactions','high'],
      ['Local Processing','Process domestically in card country','high'],
      ['Dual Message Processing','Support auth + capture flow','medium'],
      ['Single Message Processing','Combined auth and capture','medium'],
      ['Stand-In Processing','Process during network outages','critical'],
      ['EMV Chip Processing','Chip card transaction processing','high'],
      ['Contactless Processing','NFC payment processing','high'],
      ['Magstripe Fallback','Magnetic stripe processing fallback','low'],
      ['PIN Processing','PIN-based debit processing','medium'],
      ['Signature Capture','Electronic signature collection','low'],
      ['POS Terminal Management','Remote terminal management','high'],
      ['Terminal Key Management','Encryption key management for POS','critical'],
      ['P2PE Management','Point-to-point encryption','critical'],
      ['Host-to-Host Connection','Direct processor connectivity','high'],
      ['Payment Facilitator Processing','PayFac sub-merchant processing','high'],
      ['Staged Wallet Processing','Process via staged digital wallet','high'],
      ['Open Banking API','PSD2 open banking connectivity','high'],
      ['Request to Pay','Pull payment request via network','medium'],
      ['Instant Payment Rails','Real-time gross settlement','high'],
      ['ACH Processing','Automated clearing house processing','medium'],
      ['SEPA Processing','Single Euro payments area processing','medium'],
      ['Wire Transfer Processing','High-value wire processing','high'],
      ['PIX Processing','Brazilian instant payment processing','high'],
      ['UPI Processing','India unified payments processing','high'],
      ['Faster Payments','UK faster payments processing','high'],
      ['FedNow Processing','US real-time payment processing','high'],
      ['SWIFT Processing','International wire messaging','high'],
      ['Correspondent Banking','Cross-border via correspondent banks','high'],
      ['Nostro/Vostro Management','Correspondent account management','critical'],
    ]),
    // Banking Layer (50)
    ...genFeatures('banking','compliance',[
      ['KYC Verification','Know your customer identity checks','high'],
      ['KYB Verification','Know your business entity checks','high'],
      ['AML Screening','Anti-money laundering checks','critical'],
      ['Sanctions Screening','OFAC and sanctions list checks','critical'],
      ['PEP Screening','Politically exposed person checks','high'],
      ['Transaction Monitoring','Suspicious activity detection','critical'],
      ['SAR Filing','Suspicious activity report generation','critical'],
      ['CTR Filing','Currency transaction report filing','high'],
      ['Beneficial Ownership','Ultimate beneficial owner tracking','high'],
      ['Ongoing Due Diligence','Continuous customer monitoring','high'],
      ['Risk Assessment','Customer and transaction risk scoring','high'],
      ['Regulatory Reporting','Automated regulatory report generation','high'],
      ['PCI DSS Compliance','Payment card data security standard','critical'],
      ['PSD2 Compliance','EU payment services directive','high'],
      ['GDPR Compliance','Data privacy regulation compliance','high'],
      ['SOX Compliance','Financial reporting compliance','high'],
      ['State Licensing','Money transmitter license management','high'],
      ['Cross-Border Compliance','International transfer regulations','high'],
      ['Consumer Protection','Consumer rights and disclosure','medium'],
      ['Data Residency','Data storage location compliance','high'],
    ]),
    ...genFeatures('banking','risk',[
      ['Fraud Scoring','ML-based transaction fraud detection','critical'],
      ['Velocity Checks','Transaction frequency monitoring','high'],
      ['Device Fingerprinting','Device identification for risk','high'],
      ['IP Geolocation','Location-based risk assessment','medium'],
      ['Email Risk Scoring','Email address risk analysis','medium'],
      ['Phone Risk Scoring','Phone number risk verification','medium'],
      ['Address Risk Scoring','Shipping address risk analysis','medium'],
      ['Behavioral Analytics','User behavior pattern analysis','critical'],
      ['Graph Analytics','Relationship network fraud detection','critical'],
      ['Machine Learning Models','Custom fraud ML model training','critical'],
      ['Rule-Based Fraud','Configurable fraud detection rules','high'],
      ['Fraud Case Management','Investigate and manage fraud cases','high'],
      ['Chargeback Management','Dispute handling and prevention','high'],
      ['Representment','Chargeback dispute response','high'],
      ['Fraud Reporting','Fraud analytics and reporting','medium'],
      ['3DS Risk Engine','Risk assessment for 3DS decisions','high'],
      ['Account Takeover Prevention','Detect compromised accounts','critical'],
      ['Card Testing Prevention','Detect BIN attack patterns','high'],
      ['Friendly Fraud Detection','Detect first-party misuse','high'],
      ['Refund Abuse Detection','Detect refund policy abuse','high'],
    ]),
    ...genFeatures('banking','processing',[
      ['Merchant Account Management','Merchant onboarding and setup','high'],
      ['Underwriting','Merchant risk assessment','high'],
      ['FX Conversion','Foreign exchange rate management','high'],
      ['Ledger Management','Double-entry accounting ledger','critical'],
      ['Reserve Management','Merchant reserve fund management','high'],
      ['Funding Management','Merchant fund disbursement','high'],
      ['Balance Management','Real-time balance tracking','high'],
      ['Multi-Entity Management','Support multiple business entities','high'],
      ['Sub-Merchant Management','PayFac sub-merchant onboarding','high'],
      ['Pricing Engine','Dynamic pricing and fee calculation','high'],
    ]),
    // Settlement Layer (50)
    ...genFeatures('settlement','settlement',[
      ['Clearing','Transaction clearing and netting','high'],
      ['Netting','Net settlement calculation','high'],
      ['T+1 Settlement','Next-day fund settlement','high'],
      ['T+2 Settlement','Two-day fund settlement','medium'],
      ['Same-Day Settlement','Intraday fund settlement','critical'],
      ['Real-Time Settlement','Instant fund settlement','critical'],
      ['Cross-Border Settlement','International fund settlement','critical'],
      ['Multi-Currency Settlement','Settle in multiple currencies','high'],
      ['Gross Settlement','Individual transaction settlement','high'],
      ['Net Settlement','Batched net amount settlement','medium'],
      ['Settlement Reporting','Settlement report generation','medium'],
      ['Settlement Reconciliation','Match settlements to transactions','high'],
      ['Exception Management','Handle settlement exceptions','high'],
      ['Funding Reconciliation','Reconcile funding to bank','high'],
      ['Interchange Reconciliation','Reconcile interchange fees','medium'],
      ['Fee Reconciliation','Reconcile processing fees','medium'],
      ['Automated Reconciliation','ML-based auto-matching','critical'],
      ['Three-Way Reconciliation','Match PSP, acquirer, and bank','high'],
      ['Bank Statement Import','Automated bank feed integration','medium'],
      ['Reconciliation Rules','Configurable matching rules','medium'],
    ]),
    ...genFeatures('settlement','reporting',[
      ['Payout Management','Merchant fund disbursement','high'],
      ['Payout Scheduling','Configurable payout frequency','medium'],
      ['Split Payout','Distribute funds to multiple accounts','high'],
      ['Instant Payout','On-demand fund disbursement','critical'],
      ['Payout to Card','Push funds to debit card','high'],
      ['Payout to Bank','ACH/wire payout to bank account','medium'],
      ['Payout to Wallet','Disburse to digital wallet','high'],
      ['Cross-Border Payout','International fund disbursement','critical'],
      ['Mass Payout','Bulk payment processing','high'],
      ['Payout Reconciliation','Match payouts to transactions','high'],
      ['Financial Reporting','Generate financial statements','medium'],
      ['Transaction Reporting','Detailed transaction reports','medium'],
      ['Revenue Recognition','Automated revenue accounting','high'],
      ['Tax Reporting','Tax compliance reporting','high'],
      ['Dispute Reporting','Chargeback and dispute analytics','medium'],
      ['Compliance Reporting','Regulatory compliance reports','high'],
      ['Custom Dashboards','Configurable analytics dashboards','medium'],
      ['Data Export','Bulk data export capability','low'],
      ['Real-Time Analytics','Live transaction analytics','high'],
      ['Predictive Analytics','ML-based trend prediction','critical'],
      ['Anomaly Detection','Detect unusual patterns','high'],
      ['Benchmark Reporting','Industry comparison metrics','medium'],
      ['Partner Reporting','White-label partner analytics','medium'],
      ['Audit Reporting','Compliance audit trail reports','medium'],
      ['SLA Reporting','Service level agreement tracking','medium'],
      ['Operational Dashboards','System health monitoring','medium'],
      ['Executive Dashboards','C-level summary views','medium'],
      ['API Analytics','API usage and performance tracking','medium'],
      ['Customer Analytics','Customer payment behavior insights','high'],
      ['Cohort Analysis','Customer cohort tracking','high'],
    ]),
  ];

  // Insert features in batches of 50
  for (let i = 0; i < features.length; i += 50) {
    await knex('payment_features').insert(features.slice(i, i + 50));
  }

  // Get feature map for dependencies
  const featureRows = await knex('payment_features').select('id','name');
  const fm = Object.fromEntries(featureRows.map(f => [f.name, f.id]));

  // ========== FEATURE DEPENDENCIES (200) ==========
  const depPairs = [
    ['Smart Routing','BIN Lookup','depends_on',5],
    ['Cascade Routing','Smart Routing','depends_on',4],
    ['Cost-Based Routing','BIN Lookup','depends_on',3],
    ['3D Secure 2.x','PCI Vault','depends_on',4],
    ['3D Secure 2.x','Risk-Based Authentication','enhances',3],
    ['Network Tokenization','PCI Vault','depends_on',5],
    ['Network Tokenization','Gateway Tokenization','enhances',3],
    ['One-Click Pay','Saved Cards','depends_on',5],
    ['One-Click Pay','PCI Vault','depends_on',4],
    ['Recurring Billing','PCI Vault','depends_on',5],
    ['Recurring Billing','Account Updater','depends_on',4],
    ['Recurring Billing','Gateway Tokenization','depends_on',4],
    ['Account Updater','PCI Vault','depends_on',5],
    ['Account Updater','Network Tokenization','enhances',3],
    ['Fraud Scoring','Device Fingerprinting','depends_on',4],
    ['Fraud Scoring','Velocity Checks','depends_on',3],
    ['Fraud Scoring','IP Geolocation','depends_on',3],
    ['Fraud Scoring','Behavioral Analytics','enhances',4],
    ['Chargeback Management','Representment','depends_on',4],
    ['Chargeback Management','Fraud Scoring','depends_on',3],
    ['Risk-Based Authentication','Fraud Scoring','depends_on',4],
    ['Risk-Based Authentication','Device Fingerprinting','depends_on',3],
    ['Exemption Management','3D Secure 2.x','depends_on',5],
    ['Exemption Management','Risk-Based Authentication','depends_on',4],
    ['Interchange Optimization','BIN Lookup','depends_on',4],
    ['Interchange Optimization','AVS Check','depends_on',3],
    ['Multi-PSP Orchestration','Smart Routing','depends_on',5],
    ['Multi-PSP Orchestration','Failover Management','depends_on',4],
    ['Multi-PSP Orchestration','Provider Health Check','depends_on',4],
    ['Failover Management','Circuit Breaker','depends_on',4],
    ['Failover Management','Provider Health Check','depends_on',4],
    ['Split Payments','Ledger Management','depends_on',5],
    ['Split Payments','Multi-Entity Management','depends_on',4],
    ['Marketplace Checkout','Split Payments','depends_on',5],
    ['Marketplace Checkout','Sub-Merchant Management','depends_on',4],
    ['Installment Processing','Currency Conversion','depends_on',3],
    ['Installment Processing','Authorization','depends_on',4],
    ['Cross-Border Settlement','FX Conversion','depends_on',5],
    ['Cross-Border Settlement','Multi-Currency Settlement','depends_on',4],
    ['Cross-Border Settlement','Correspondent Banking','depends_on',4],
    ['Multi-Currency Processing','FX Conversion','depends_on',5],
    ['Multi-Currency Processing','Currency Conversion','depends_on',4],
    ['Payout to Card','Visa Direct','depends_on',4],
    ['Payout to Card','Mastercard Send','depends_on',4],
    ['Instant Payout','Same-Day Settlement','depends_on',4],
    ['Instant Payout','Real-Time Settlement','enhances',3],
    ['Settlement Reconciliation','Bank Statement Import','depends_on',4],
    ['Settlement Reconciliation','Automated Reconciliation','enhances',3],
    ['Three-Way Reconciliation','Settlement Reconciliation','depends_on',5],
    ['Three-Way Reconciliation','Fee Reconciliation','depends_on',4],
    ['Soft Decline Handling','Decline Code Analysis','depends_on',5],
    ['Retry Orchestration','Soft Decline Handling','depends_on',4],
    ['Retry Orchestration','Cascade Routing','enhances',3],
    ['Revenue Optimization','Smart Routing','depends_on',5],
    ['Revenue Optimization','Retry Orchestration','depends_on',4],
    ['Revenue Optimization','Interchange Optimization','depends_on',3],
    ['Rapid Dispute Resolution','Chargeback Management','depends_on',4],
    ['Card Testing Prevention','Velocity Checks','depends_on',5],
    ['Card Testing Prevention','Device Fingerprinting','depends_on',3],
    ['Account Takeover Prevention','Behavioral Analytics','depends_on',5],
    ['Account Takeover Prevention','Device Fingerprinting','depends_on',4],
    ['Token Lifecycle Management','Gateway Tokenization','depends_on',5],
    ['Token Migration','Token Lifecycle Management','depends_on',5],
    ['Token Migration','Network Tokenization','depends_on',4],
    ['Cross-Channel Tokenization','Token Lifecycle Management','depends_on',4],
    ['Cross-Channel Tokenization','Network Tokenization','enhances',3],
    ['Network Token Lifecycle','Network Tokenization','depends_on',5],
    ['Network Token Lifecycle','Scheme Token Provisioning','depends_on',4],
    ['Delegated Authentication','3D Secure 2.x','depends_on',5],
    ['Delegated Authentication','Biometric Authentication','enhances',3],
    ['Step-Up Authentication','Risk-Based Authentication','depends_on',4],
    ['Step-Up Authentication','3D Secure 2.x','depends_on',3],
    ['Biometric Prompt','Biometric Authentication','depends_on',5],
    ['Express Checkout','One-Click Pay','depends_on',4],
    ['Express Checkout','Saved Cards','depends_on',3],
    ['Subscription Signup','Recurring Billing','depends_on',5],
    ['Trial Period Flow','Subscription Signup','depends_on',4],
    ['Upgrade/Downgrade Flow','Subscription Signup','depends_on',4],
    ['Upgrade/Downgrade Flow','Pricing Engine','depends_on',3],
    ['Pay-by-Bank UI','Open Banking API','depends_on',5],
    ['Mass Payout','Batch Processing','depends_on',4],
    ['Mass Payout','Payout Management','depends_on',4],
    ['Split Payout','Split Payments','depends_on',4],
    ['Split Payout','Payout Management','depends_on',4],
    ['Predictive Analytics','Real-Time Analytics','depends_on',4],
    ['Predictive Analytics','Machine Learning Models','depends_on',3],
    ['Anomaly Detection','Real-Time Analytics','depends_on',4],
    ['Anomaly Detection','Machine Learning Models','depends_on',3],
    ['Custom Dashboards','Transaction Reporting','depends_on',3],
    ['Custom Dashboards','Financial Reporting','depends_on',3],
    ['SLA Monitoring','Provider Health Check','depends_on',4],
    ['SLA Monitoring','Provider Scorecard','depends_on',3],
    ['Canary Deployment','Feature Flag Routing','depends_on',4],
    ['Canary Deployment','Routing Simulation','depends_on',3],
    ['A/B Testing Routing','Routing Analytics','depends_on',4],
    ['Routing Simulation','Rules-Based Routing','depends_on',4],
    ['Dynamic MID Selection','BIN Lookup','depends_on',3],
    ['Payment Facilitator Processing','Sub-Merchant Management','depends_on',5],
    ['Payment Facilitator Processing','Merchant Account Management','depends_on',4],
    ['Staged Wallet Processing','Gateway Tokenization','depends_on',4],
    ['Graph Analytics','Fraud Scoring','depends_on',4],
    ['Graph Analytics','Machine Learning Models','depends_on',3],
    ['Friendly Fraud Detection','Chargeback Management','depends_on',4],
    ['Friendly Fraud Detection','Behavioral Analytics','depends_on',3],
    ['Refund Abuse Detection','Behavioral Analytics','depends_on',3],
    ['SAR Filing','Transaction Monitoring','depends_on',5],
    ['CTR Filing','Transaction Monitoring','depends_on',5],
    ['Ongoing Due Diligence','KYC Verification','depends_on',5],
    ['Ongoing Due Diligence','AML Screening','depends_on',4],
    ['Beneficial Ownership','KYB Verification','depends_on',5],
    ['PSD2 Compliance','3D Secure 2.x','depends_on',4],
    ['PSD2 Compliance','Open Banking API','depends_on',4],
    ['Revenue Recognition','Ledger Management','depends_on',5],
    ['Revenue Recognition','Financial Reporting','depends_on',4],
    ['Cohort Analysis','Customer Analytics','depends_on',4],
    ['Clearing','Netting','depends_on',4],
    ['Net Settlement','Netting','depends_on',5],
    ['Funding Management','Balance Management','depends_on',4],
    ['Reserve Management','Balance Management','depends_on',4],
    ['Payout Scheduling','Payout Management','depends_on',4],
    ['Payout Reconciliation','Payout Management','depends_on',4],
    ['Authorization Optimization','BIN Lookup','depends_on',4],
    ['Authorization Optimization','Decline Code Analysis','depends_on',3],
    ['Network Score','Network Fraud Signals','depends_on',3],
    ['ISO 8583 Messaging','Host-to-Host Connection','depends_on',4],
    ['EMV Chip Processing','Terminal Key Management','depends_on',4],
    ['Contactless Processing','EMV Chip Processing','depends_on',3],
    ['P2PE Management','Terminal Key Management','depends_on',5],
    ['PIN Processing','Terminal Key Management','depends_on',4],
    ['Local Processing','Geographic Routing','depends_on',4],
    ['Localized Checkout','Currency Selector','depends_on',3],
    ['Promo Code Input','Discount Application','depends_on',3],
    ['Gift Card Input','Balance Inquiry','depends_on',3],
    ['Idempotency Service','API Gateway','depends_on',3],
    ['Rate Limiting','API Gateway','depends_on',3],
    ['Provider Normalization','Error Code Mapping','depends_on',4],
    ['Migration Orchestration','Provider Normalization','depends_on',4],
    ['Migration Orchestration','Token Migration','depends_on',5],
    ['DPAN Management','Network Tokenization','depends_on',5],
    ['Token Requestor ID','Network Tokenization','depends_on',5],
    ['Request to Pay','Open Banking API','depends_on',4],
    ['Instant Payment Rails','Real-Time Settlement','depends_on',5],
    ['PIX Processing','Instant Payment Rails','depends_on',4],
    ['FedNow Processing','Instant Payment Rails','depends_on',4],
    ['Faster Payments','Instant Payment Rails','depends_on',4],
    ['SWIFT Processing','Correspondent Banking','depends_on',4],
    ['Data Residency','GDPR Compliance','depends_on',3],
    ['Regulatory Reporting','Compliance Reporting','depends_on',4],
    ['Fraud Case Management','Fraud Scoring','depends_on',4],
    ['Fraud Case Management','Rule-Based Fraud','depends_on',3],
    ['3DS Risk Engine','Fraud Scoring','depends_on',4],
    ['3DS Risk Engine','3D Secure 2.x','depends_on',5],
    ['Merchant Account Management','Underwriting','depends_on',4],
    ['Sub-Merchant Management','Merchant Account Management','depends_on',5],
    ['Pricing Engine','Multi-Entity Management','depends_on',3],
    ['Real-Time Analytics','Event Bus','depends_on',3],
    ['Operational Dashboards','Real-Time Analytics','depends_on',4],
    ['Executive Dashboards','Custom Dashboards','depends_on',3],
    ['API Analytics','API Gateway','depends_on',4],
    ['Webhook Management','Event Bus','depends_on',3],
    ['Audit Trail','Event Bus','depends_on',3],
    ['Configuration Service','Provider Sandbox','enhances',2],
    ['Payment Intent Management','Status Synchronization','depends_on',3],
    ['Rollback Orchestration','Payment Intent Management','depends_on',4],
    ['Error Recovery UI','Error Code Mapping','depends_on',3],
    ['Cart Recovery','Payment Status Page','depends_on',3],
    ['Auto-Capture','Authorization','depends_on',4],
    ['Delayed Capture','Pre-Authorization','depends_on',4],
    ['Partial Capture','Authorization','depends_on',4],
    ['Partial Refund','Refund','depends_on',4],
    ['Reversal Processing','Authorization','depends_on',4],
    ['Credit Processing','Ledger Management','depends_on',4],
    ['Surcharge Calculation','Pricing Engine','depends_on',3],
    ['Tax Calculation','Pricing Engine','depends_on',3],
    ['Tax Reporting','Tax Calculation','depends_on',4],
    ['Dispute Reporting','Chargeback Management','depends_on',4],
    ['POS Integration','EMV Chip Processing','depends_on',4],
    ['POS Integration','Contactless Processing','depends_on',3],
    ['POS Terminal Management','POS Integration','depends_on',4],
    ['Voice Payment','Biometric Authentication','depends_on',4],
    ['Chatbot Payment','Payment Links','depends_on',3],
    ['Social Commerce Checkout','Embedded Checkout','depends_on',3],
    ['Crypto Payment UI','Crypto Payment UI','depends_on',1], // self-ref removed below
    ['Invoice Payment Portal','Payment Links','depends_on',3],
    ['Recurring Donation','Recurring Billing','depends_on',4],
    ['Payment Animation','Payment Status Page','depends_on',2],
    ['Email Risk Scoring','Fraud Scoring','enhances',2],
    ['Phone Risk Scoring','Fraud Scoring','enhances',2],
    ['Address Risk Scoring','AVS Check','depends_on',3],
    ['Partner Reporting','Custom Dashboards','depends_on',3],
    ['Audit Reporting','Audit Trail','depends_on',4],
    ['Batch Authorization','Authorization','depends_on',4],
    ['Scheduled Payments','Batch Processing','depends_on',3],
  ];

  // Filter valid deps and remove self-references
  const validDeps = depPairs
    .filter(([src,tgt]) => fm[src] && fm[tgt] && src !== tgt)
    .map(([src,tgt,rel,str]) => ({
      source_feature_id: fm[src], target_feature_id: fm[tgt],
      relationship_type: rel, strength: str, description: `${src} ${rel} ${tgt}`
    }));

  for (let i = 0; i < validDeps.length; i += 50) {
    await knex('feature_dependencies').insert(validDeps.slice(i, i + 50));
  }

  // ========== BUSINESS RULES (150) ==========
  const ruleTemplates = [
    ['validation','warning'], ['validation','critical'], ['routing','info'],
    ['routing','warning'], ['risk','critical'], ['risk','warning'],
    ['compliance','critical'], ['compliance','warning'], ['operational','info'],
    ['operational','warning'],
  ];

  const ruleData = [
    ['CVV Required for CNP','Transaction is card-not-present','CVV must be provided and validated','validation','critical'],
    ['AVS Match Required','Billing address provided','AVS response must be match or partial match','validation','warning'],
    ['Minimum Amount Check','Transaction amount below threshold','Reject transactions below minimum amount','validation','info'],
    ['Maximum Amount Check','Transaction amount exceeds threshold','Flag for manual review or decline','validation','warning'],
    ['Currency Validation','Multi-currency transaction','Verify currency is supported for merchant','validation','critical'],
    ['Card Expiry Check','Card expiration date provided','Reject expired cards before sending to network','validation','critical'],
    ['BIN Country Match','Cardholder country differs from BIN country','Flag potential cross-border fraud','validation','warning'],
    ['Duplicate Detection','Same amount and card within 5 minutes','Prevent duplicate charges','validation','critical'],
    ['Luhn Check','Card number provided','Validate card number passes Luhn algorithm','validation','critical'],
    ['MCC Validation','Merchant category code assigned','Verify MCC is valid and active','validation','info'],
    ['3DS Required EEA','Transaction originates from EEA','Apply SCA via 3D Secure 2.x','compliance','critical'],
    ['3DS Exemption TRA','Low-risk transaction under threshold','Apply TRA exemption if eligible','compliance','warning'],
    ['3DS Exemption Low Value','Transaction under 30 EUR','Apply low-value exemption','compliance','info'],
    ['PCI Scope Check','Card data handled','Ensure PCI DSS compliance level met','compliance','critical'],
    ['Data Retention Limit','Customer data stored','Delete data after retention period','compliance','warning'],
    ['GDPR Consent','EU customer data processed','Verify data processing consent','compliance','critical'],
    ['Sanctions Check','International transaction','Screen against sanctions lists','compliance','critical'],
    ['AML Threshold','Transaction exceeds reporting threshold','File CTR if over $10,000','compliance','critical'],
    ['Cross-Border Reporting','International transfer over limit','Report to regulatory authority','compliance','warning'],
    ['Consumer Disclosure','New payment method added','Provide required fee disclosures','compliance','info'],
    ['Route by BIN Country','Card BIN country identified','Route to local acquirer in card country','routing','info'],
    ['Route by Cost','Multiple acquirers available','Select lowest-cost acquirer','routing','info'],
    ['Route by Approval Rate','Historical approval data available','Route to highest-approval acquirer for BIN','routing','info'],
    ['Cascade on Soft Decline','Soft decline received','Retry with secondary acquirer','routing','warning'],
    ['Block on Hard Decline','Hard decline received','Do not retry, return decline to customer','routing','critical'],
    ['Volume Balancing','Multiple acquirers configured','Distribute volume per contractual minimums','routing','info'],
    ['MID Rotation','MID approaching volume cap','Switch to alternate MID','routing','warning'],
    ['Currency Routing','Non-domestic currency','Route to acquirer supporting currency','routing','info'],
    ['High-Risk MCC Routing','Merchant in high-risk category','Route to specialized acquirer','routing','warning'],
    ['Network Preference','Transaction eligible for multiple networks','Route per network cost/approval preference','routing','info'],
    ['Velocity Limit Per Card','Same card used multiple times','Block after N transactions in time window','risk','critical'],
    ['Velocity Limit Per IP','Same IP multiple transactions','Flag for review after threshold','risk','warning'],
    ['High Amount Alert','Amount significantly above average','Flag for manual review','risk','warning'],
    ['New Card Alert','First transaction with this card','Apply enhanced fraud checks','risk','warning'],
    ['Country Mismatch','IP country differs from billing','Increase risk score','risk','warning'],
    ['Device Change Alert','Known customer, new device','Require step-up authentication','risk','warning'],
    ['Rapid Succession','Multiple transactions within seconds','Block as potential card testing','risk','critical'],
    ['Fraud Score Threshold','Risk score above threshold','Decline or route to 3DS','risk','critical'],
    ['Chargeback Ratio Alert','Merchant chargeback rate above 0.9%','Alert and review merchant account','risk','critical'],
    ['Refund Ratio Alert','Refund rate above 10%','Flag merchant for review','risk','warning'],
    ['Retry Delay','Transaction just declined','Wait minimum period before retry','operational','info'],
    ['Retry Limit','Multiple retries attempted','Stop after maximum retry count','operational','warning'],
    ['Timeout Handling','Provider response timeout','Cancel and retry with alternate','operational','warning'],
    ['Queue Depth Alert','Processing queue backing up','Alert operations team','operational','warning'],
    ['Settlement Deadline','Approaching settlement cutoff','Process pending captures','operational','critical'],
    ['Reconciliation Gap','Unmatched transactions detected','Flag for manual reconciliation','operational','warning'],
    ['Provider Degradation','Error rate above threshold','Activate circuit breaker','operational','critical'],
    ['Batch Size Limit','Batch processing initiated','Limit batch to maximum size','operational','info'],
    ['Webhook Retry','Webhook delivery failed','Retry with exponential backoff','operational','info'],
    ['Token Expiry Alert','Network token expiring soon','Trigger token renewal','operational','warning'],
  ];

  // Generate 150 rules by combining with features
  const featureNames = featureRows.map(f => f.name);
  const businessRules = [];
  for (let i = 0; i < ruleData.length; i++) {
    const [name, cond, behavior, type, severity] = ruleData[i];
    // Assign to a relevant feature
    const featureIdx = i % featureNames.length;
    const featureId = featureRows[featureIdx].id;
    businessRules.push({
      feature_id: featureId, rule_name: name,
      condition: cond, expected_behavior: behavior,
      rule_type: type, severity: severity, metadata: '{}'
    });
  }

  // Generate additional rules to reach 150
  const extraRulePatterns = [
    ['Max Retry Count','Retry count exceeds limit','Stop retrying and return final decline','operational','warning'],
    ['Settlement Currency Check','Settlement currency configured','Verify settlement currency matches expectation','validation','info'],
    ['Merchant Active Check','Transaction received','Verify merchant account is active','validation','critical'],
    ['Rate Limit Exceeded','API call rate above limit','Return 429 and queue request','operational','warning'],
    ['Token Format Validation','Token provided in request','Validate token format and checksum','validation','info'],
    ['Capture Within Window','Capture requested','Verify within authorization hold period','validation','warning'],
    ['Refund Window Check','Refund requested','Verify within refund eligibility window','validation','warning'],
    ['Minimum Payout Amount','Payout triggered','Verify amount meets minimum payout threshold','operational','info'],
    ['Reserve Calculation','Settlement processed','Calculate and hold required reserve amount','operational','warning'],
    ['FX Rate Staleness','Cross-border transaction','Verify FX rate is current (not stale)','validation','warning'],
  ];

  for (let i = 0; i < 100; i++) {
    const pattern = extraRulePatterns[i % extraRulePatterns.length];
    const [name, cond, behavior, type, severity] = pattern;
    const featureId = featureRows[i % featureRows.length].id;
    businessRules.push({
      feature_id: featureId, rule_name: `${name} #${Math.floor(i/10)+1}`,
      condition: cond, expected_behavior: behavior,
      rule_type: type, severity: severity, metadata: '{}'
    });
  }

  for (let i = 0; i < businessRules.length; i += 50) {
    await knex('feature_business_rules').insert(businessRules.slice(i, i + 50));
  }

  // ========== PAYMENT RAILS (8) ==========
  await knex('payment_rails').insert([
    { name:'Cards', description:'Credit and debit card payments via Visa, Mastercard, Amex, and other networks', type:'card', supported_currencies:'{USD,EUR,GBP,BRL,JPY,AUD,CAD}', supported_countries:'{US,GB,DE,FR,BR,JP,AU,CA,MX}', actors:'{Issuer,Acquirer,Network,Merchant}', characteristics:'{"settlement_time":"T+1 to T+3","fees":"1.5-3.5%","reversibility":"chargeback","global":true}' },
    { name:'PIX', description:'Brazilian instant payment system operated by Central Bank', type:'bank_transfer', supported_currencies:'{BRL}', supported_countries:'{BR}', actors:'{Central Bank,PSP,Merchant,Consumer}', characteristics:'{"settlement_time":"instant","fees":"free for consumers","reversibility":"limited","real_time":true}' },
    { name:'ACH', description:'Automated Clearing House for US bank transfers', type:'bank_transfer', supported_currencies:'{USD}', supported_countries:'{US}', actors:'{NACHA,ODFI,RDFI,Federal Reserve}', characteristics:'{"settlement_time":"1-3 days","fees":"$0.20-0.50","reversibility":"ACH return","batch":true}' },
    { name:'SEPA', description:'Single Euro Payments Area bank transfers', type:'bank_transfer', supported_currencies:'{EUR}', supported_countries:'{DE,FR,NL,ES,IT,BE,AT,PT,IE,FI}', actors:'{EPC,PSP,Bank,Merchant}', characteristics:'{"settlement_time":"1-2 days","fees":"€0.20-0.50","reversibility":"SEPA recall"}' },
    { name:'Wire Transfer', description:'High-value bank-to-bank wire transfers', type:'bank_transfer', supported_currencies:'{USD,EUR,GBP,CHF,JPY}', supported_countries:'{US,GB,DE,CH,JP}', actors:'{Originating Bank,Correspondent Bank,Beneficiary Bank}', characteristics:'{"settlement_time":"same day to T+2","fees":"$15-50","reversibility":"difficult","high_value":true}' },
    { name:'Digital Wallets', description:'PayPal, Apple Pay, Google Pay and other digital wallets', type:'wallet', supported_currencies:'{USD,EUR,GBP,BRL,AUD}', supported_countries:'{US,GB,DE,FR,BR,AU,CA}', actors:'{Wallet Provider,Network,Merchant}', characteristics:'{"settlement_time":"instant to T+1","fees":"2.5-3.5%","reversibility":"dispute"}' },
    { name:'UPI', description:'Unified Payments Interface for India', type:'bank_transfer', supported_currencies:'{INR}', supported_countries:'{IN}', actors:'{NPCI,PSP,Bank,Merchant}', characteristics:'{"settlement_time":"instant","fees":"free under limits","real_time":true}' },
    { name:'Crypto', description:'Cryptocurrency and stablecoin payments', type:'crypto', supported_currencies:'{BTC,ETH,USDC,USDT}', supported_countries:'{US,GB,DE,SG,BR}', actors:'{Blockchain,Exchange,Wallet Provider,Merchant}', characteristics:'{"settlement_time":"minutes to hours","fees":"variable gas fees","reversibility":"none","borderless":true}' },
  ]);

  const railRows = await knex('payment_rails').select('id','name');
  const rm = Object.fromEntries(railRows.map(r => [r.name, r.id]));

  // ========== ACTORS (25) ==========
  await knex('actors').insert([
    { name:'Consumer', description:'End customer making a payment', type:'consumer', category:'financial', capabilities:'{initiate_payment,dispute_transaction,manage_payment_methods}' },
    { name:'Merchant', description:'Business accepting payments', type:'merchant', category:'financial', capabilities:'{accept_payments,issue_refunds,manage_subscriptions}' },
    { name:'Payment Service Provider', description:'Technology platform connecting merchants to acquirers', type:'psp', category:'technology', capabilities:'{transaction_processing,tokenization,routing,reporting}' },
    { name:'Acquirer', description:'Bank that processes payments on behalf of merchants', type:'acquirer', category:'financial', capabilities:'{authorization,settlement,merchant_funding,risk_management}' },
    { name:'Issuer', description:'Bank that issues payment cards to consumers', type:'issuer', category:'financial', capabilities:'{card_issuance,authorization_approval,fraud_monitoring,billing}' },
    { name:'Card Network', description:'Payment scheme connecting issuers and acquirers', type:'network', category:'infrastructure', capabilities:'{transaction_routing,rules_enforcement,dispute_management,tokenization}' },
    { name:'Payment Facilitator', description:'Platform enabling sub-merchant payment acceptance', type:'psp', category:'technology', capabilities:'{sub_merchant_onboarding,split_payments,compliance,reporting}' },
    { name:'Payment Gateway', description:'Technology connecting merchant to acquirer', type:'psp', category:'technology', capabilities:'{authorization_relay,tokenization,encryption,api_management}' },
    { name:'Fraud Prevention Provider', description:'Specialized fraud detection service', type:'psp', category:'technology', capabilities:'{risk_scoring,device_fingerprinting,identity_verification}' },
    { name:'Central Bank', description:'National monetary authority', type:'regulator', category:'regulatory', capabilities:'{monetary_policy,payment_system_oversight,instant_payment_operation}' },
    { name:'Regulatory Body', description:'Financial services regulator', type:'regulator', category:'regulatory', capabilities:'{licensing,compliance_enforcement,consumer_protection}' },
    { name:'Processor', description:'Third-party transaction processor', type:'psp', category:'technology', capabilities:'{authorization_processing,settlement,batch_processing}' },
    { name:'Independent Sales Organization', description:'Agent selling merchant services', type:'merchant', category:'financial', capabilities:'{merchant_acquisition,terminal_deployment,support}' },
    { name:'Payment Orchestrator', description:'Platform managing multi-provider payment flows', type:'psp', category:'technology', capabilities:'{smart_routing,failover,provider_management,analytics}' },
    { name:'Wallet Provider', description:'Digital wallet service provider', type:'wallet_provider', category:'technology', capabilities:'{balance_management,p2p_transfers,payment_initiation}' },
    { name:'BNPL Provider', description:'Buy now pay later service', type:'wallet_provider', category:'financial', capabilities:'{credit_assessment,installment_management,merchant_integration}' },
    { name:'Correspondent Bank', description:'Bank providing services on behalf of foreign banks', type:'issuer', category:'financial', capabilities:'{cross_border_transfers,fx_conversion,clearing}' },
    { name:'Clearing House', description:'Central counterparty for transaction clearing', type:'network', category:'infrastructure', capabilities:'{clearing,netting,settlement_finality}' },
    { name:'Token Service Provider', description:'Network tokenization service', type:'network', category:'infrastructure', capabilities:'{token_provisioning,token_lifecycle,cryptogram_generation}' },
    { name:'3DS Server Provider', description:'3D Secure authentication service', type:'psp', category:'technology', capabilities:'{authentication,risk_assessment,exemption_management}' },
    { name:'KYC Provider', description:'Identity verification service', type:'psp', category:'technology', capabilities:'{identity_verification,document_validation,sanctions_screening}' },
    { name:'Reconciliation Service', description:'Automated reconciliation platform', type:'psp', category:'technology', capabilities:'{transaction_matching,exception_management,reporting}' },
    { name:'Tax Authority', description:'Government tax collection agency', type:'regulator', category:'regulatory', capabilities:'{tax_collection,compliance_audit,reporting_requirements}' },
    { name:'Marketplace Platform', description:'Multi-sided platform connecting buyers and sellers', type:'merchant', category:'technology', capabilities:'{order_management,seller_management,split_payments}' },
    { name:'Terminal Manufacturer', description:'POS hardware manufacturer', type:'merchant', category:'technology', capabilities:'{terminal_production,software_updates,key_injection}' },
  ]);

  // ========== TRANSACTION FLOWS (30) ==========
  const flows = [
    ['Card Purchase','Standard card payment authorization and capture','card_payment','Cards','{Consumer,Merchant,PSP,Acquirer,Network,Issuer}','{Authorization,3D Secure 2.x,BIN Lookup,Fraud Scoring}'],
    ['Card Refund','Return funds to original payment method','card_payment','Cards','{Merchant,PSP,Acquirer,Network,Issuer}','{Refund,Ledger Management}'],
    ['PIX Payment','Instant payment via Brazilian PIX system','pix','PIX','{Consumer,Merchant,PSP,Central Bank}','{PIX Processing,QR Code Payment}'],
    ['PIX Refund','Refund via PIX instant payment','pix','PIX','{Merchant,PSP,Central Bank}','{PIX Processing,Refund}'],
    ['ACH Debit','Pull payment from US bank account','ach','ACH','{Merchant,PSP,NACHA}','{ACH Processing,KYC Verification}'],
    ['ACH Credit','Push payment to US bank account','ach','ACH','{Merchant,PSP,NACHA}','{ACH Processing,Payout to Bank}'],
    ['SEPA Transfer','Euro-denominated bank transfer','bank_transfer','SEPA','{Consumer,Merchant,PSP}','{SEPA Processing,Open Banking API}'],
    ['Wire Transfer','High-value international wire payment','bank_transfer','Wire Transfer','{Merchant,Correspondent Bank}','{Wire Transfer Processing,SWIFT Processing,FX Conversion}'],
    ['Apple Pay Payment','In-app or web payment via Apple Pay','wallet','Digital Wallets','{Consumer,Merchant,PSP,Network}','{Contactless Processing,Network Tokenization}'],
    ['Google Pay Payment','Payment via Google Pay','wallet','Digital Wallets','{Consumer,Merchant,PSP,Network}','{Contactless Processing,Network Tokenization}'],
    ['Cross-Border Card','International card payment with FX','crossborder','Cards','{Consumer,Merchant,PSP,Acquirer,Network,Issuer}','{Cross-Border Optimization,Currency Conversion,FX Conversion}'],
    ['Marketplace Split Payment','Multi-seller payment with split','marketplace','Cards','{Consumer,Marketplace Platform,PSP,Acquirer}','{Split Payments,Sub-Merchant Management}'],
    ['Subscription Initial','First subscription payment setup','subscription','Cards','{Consumer,Merchant,PSP}','{Recurring Billing,PCI Vault,Gateway Tokenization}'],
    ['Subscription Renewal','Recurring subscription charge','subscription','Cards','{Merchant,PSP,Acquirer,Network,Issuer}','{Recurring Billing,Account Updater,Network Tokenization}'],
    ['BNPL Purchase','Buy now pay later transaction','bnpl','Cards','{Consumer,BNPL Provider,Merchant}','{Installment Processing,Credit Processing}'],
    ['Payout to Bank Account','Merchant fund disbursement via bank','payout','ACH','{PSP,Merchant,Acquirer}','{Payout to Bank,Payout Management}'],
    ['Payout to Debit Card','Push funds to merchant debit card','payout','Cards','{PSP,Merchant,Network}','{Payout to Card,Visa Direct}'],
    ['Chargeback Flow','Customer-initiated payment dispute','dispute','Cards','{Consumer,Issuer,Network,Acquirer,Merchant}','{Chargeback Management,Representment}'],
    ['Pre-Auth and Capture','Authorize then capture later','card_payment','Cards','{Consumer,Merchant,PSP,Acquirer,Network,Issuer}','{Pre-Authorization,Delayed Capture}'],
    ['Incremental Auth','Increase authorized amount','card_payment','Cards','{Merchant,PSP,Acquirer,Network,Issuer}','{Incremental Authorization,Authorization}'],
    ['3DS Authentication','Standalone 3DS verification','authentication','Cards','{Consumer,Merchant,3DS Server Provider,Issuer}','{3D Secure 2.x,Risk-Based Authentication}'],
    ['Tokenization Flow','Store card and generate token','tokenization','Cards','{Consumer,Merchant,PSP}','{Gateway Tokenization,PCI Vault,Card Verification}'],
    ['Account Verification','Zero-amount card validation','verification','Cards','{Merchant,PSP,Acquirer,Network,Issuer}','{Card Verification,AVS Check}'],
    ['Balance Inquiry','Check prepaid/gift card balance','inquiry','Cards','{Consumer,Merchant,PSP,Issuer}','{Balance Inquiry}'],
    ['Card-on-File Setup','Store card for future payments','tokenization','Cards','{Consumer,Merchant,PSP}','{Saved Cards,Network Tokenization,PCI Vault}'],
    ['Installment Payment','Payment in installments','installment','Cards','{Consumer,Merchant,PSP,Acquirer}','{Installment Processing,Installment Selection UI}'],
    ['Crypto Payment','Cryptocurrency payment flow','crypto','Crypto','{Consumer,Merchant,Exchange}','{Crypto Payment UI}'],
    ['QR Code Payment','Scan QR to initiate payment','qr_payment','PIX','{Consumer,Merchant,PSP}','{QR Code Payment,PIX Processing}'],
    ['Payment Link','Pay via shared link','payment_link','Cards','{Consumer,Merchant,PSP}','{Payment Links,Hosted Payment Page}'],
    ['Invoice Payment','Online invoice payment','invoice','Cards','{Consumer,Merchant,PSP}','{Invoice Payment Portal,Payment Links}'],
  ];

  for (const [name,desc,ftype,rail,actors,feats] of flows) {
    await knex('transaction_flows').insert({
      name, description: desc, flow_type: ftype,
      rail_id: rm[rail] || null,
      actors: actors, features_used: feats
    });
  }

  // Get flow IDs for steps
  const flowRows = await knex('transaction_flows').select('id','name');
  const flowMap = Object.fromEntries(flowRows.map(f => [f.name, f.id]));

  // ========== TRANSACTION STEPS (sample for key flows) ==========
  const stepSets = {
    'Card Purchase': [
      [1,'Customer Initiates Payment','Consumer selects items and enters payment details','Consumer','request','{Checkout UI,Card Input Validation}'],
      [2,'Fraud Screening','PSP evaluates transaction risk score','Payment Service Provider','validation','{Fraud Scoring,Velocity Checks,Device Fingerprinting}'],
      [3,'3DS Authentication','Cardholder authentication if required','3DS Server Provider','validation','{3D Secure 2.x,Risk-Based Authentication}'],
      [4,'Authorization Request','PSP sends auth request to acquirer','Payment Service Provider','processing','{Authorization,Smart Routing,BIN Lookup}'],
      [5,'Network Routing','Acquirer routes to card network','Acquirer','processing','{ISO 8583 Messaging}'],
      [6,'Issuer Decision','Issuer approves or declines','Issuer','processing','{Authorization}'],
      [7,'Response Return','Auth response returned to merchant','Payment Service Provider','response','{Payment Status Page}'],
      [8,'Capture','Merchant captures the authorized payment','Merchant','processing','{Capture,Auto-Capture}'],
    ],
    'PIX Payment': [
      [1,'QR Code Generation','Merchant generates PIX QR code','Merchant','request','{QR Code Payment}'],
      [2,'Customer Scans','Consumer scans QR with banking app','Consumer','request','{Pay-by-Bank UI}'],
      [3,'Bank Authorization','Customer bank validates and approves','Issuer','processing','{PIX Processing}'],
      [4,'Instant Transfer','Central Bank processes instant transfer','Central Bank','processing','{Instant Payment Rails,Real-Time Settlement}'],
      [5,'Merchant Notification','Merchant receives payment confirmation','Payment Service Provider','response','{Webhook Management}'],
      [6,'Settlement Complete','Funds available to merchant instantly','Central Bank','response','{Real-Time Settlement}'],
    ],
    'Cross-Border Card': [
      [1,'Payment Initiation','Customer initiates international payment','Consumer','request','{Checkout UI,Currency Selector}'],
      [2,'Currency Detection','System detects cross-border transaction','Payment Service Provider','validation','{BIN Lookup,Currency Conversion}'],
      [3,'FX Conversion','Apply foreign exchange rate','Payment Service Provider','processing','{FX Conversion,Multi-Currency Processing}'],
      [4,'Local Routing','Route to local acquirer if available','Payment Service Provider','processing','{Geographic Routing,Local Processing}'],
      [5,'Authorization','Process authorization through network','Acquirer','processing','{Authorization,Cross-Border Optimization}'],
      [6,'Issuer Approval','Foreign issuer approves transaction','Issuer','processing','{Authorization}'],
      [7,'Settlement','Cross-border settlement processing','Clearing House','processing','{Cross-Border Settlement,Multi-Currency Settlement}'],
    ],
    'Chargeback Flow': [
      [1,'Consumer Disputes','Cardholder contacts issuer about charge','Consumer','request','{Chargeback Management}'],
      [2,'Issuer Files Chargeback','Issuer initiates chargeback via network','Issuer','processing','{Chargeback Management}'],
      [3,'Acquirer Notified','Acquirer receives and routes to merchant','Acquirer','processing','{Chargeback Management}'],
      [4,'Merchant Review','Merchant reviews dispute evidence','Merchant','validation','{Fraud Case Management}'],
      [5,'Representment','Merchant submits evidence to fight dispute','Merchant','processing','{Representment}'],
      [6,'Network Decision','Network arbitrates if needed','Card Network','processing','{Rapid Dispute Resolution}'],
    ],
    'Marketplace Split Payment': [
      [1,'Multi-Seller Cart','Customer checks out with items from multiple sellers','Consumer','request','{Marketplace Checkout}'],
      [2,'Split Calculation','Calculate split amounts per seller','Payment Service Provider','processing','{Split Payments,Pricing Engine}'],
      [3,'Single Authorization','Authorize total amount','Payment Service Provider','processing','{Authorization,Smart Routing}'],
      [4,'Capture and Split','Capture and split funds','Payment Service Provider','processing','{Split Payments,Ledger Management}'],
      [5,'Seller Payouts','Distribute funds to each seller','Payment Service Provider','processing','{Split Payout,Payout Management}'],
      [6,'Platform Fee','Deduct platform commission','Marketplace Platform','processing','{Pricing Engine,Revenue Recognition}'],
    ],
  };

  for (const [flowName, steps] of Object.entries(stepSets)) {
    if (!flowMap[flowName]) continue;
    for (const [order,name,desc,actor,type,feats] of steps) {
      await knex('transaction_steps').insert({
        flow_id: flowMap[flowName], step_order: order,
        name, description: desc, actor, step_type: type,
        features_involved: feats
      });
    }
  }

  console.log('Seed data inserted successfully');
  console.log(`Features: ${features.length}`);
  console.log(`Dependencies: ${validDeps.length}`);
  console.log(`Business Rules: ${businessRules.length}`);
  console.log(`Flows: ${flows.length}`);
};
